// Code generated by Kitex v0.8.0. DO NOT EDIT.

package echo2

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/felix021/dubbo-p2/kitex_gen/java"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.TProtocol(nil)
	_ = java.KitexUnusedProtection
)

type TestService2EchoArgs struct {
	Req *EchoRequest `thrift:"req,1" frugal:"1,default,EchoRequest" json:"req"`
}

func NewTestService2EchoArgs() *TestService2EchoArgs {
	return &TestService2EchoArgs{}
}

func (p *TestService2EchoArgs) InitDefault() {
	*p = TestService2EchoArgs{}
}

var TestService2EchoArgs_Req_DEFAULT *EchoRequest

func (p *TestService2EchoArgs) GetReq() (v *EchoRequest) {
	if !p.IsSetReq() {
		return TestService2EchoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TestService2EchoArgs) SetReq(val *EchoRequest) {
	p.Req = val
}

func (p *TestService2EchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestService2EchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestService2EchoArgs(%+v)", *p)
}
func (p *TestService2EchoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestService2EchoResult struct {
	Success *EchoResponse `thrift:"success,0,optional" frugal:"0,optional,EchoResponse" json:"success,omitempty"`
}

func NewTestService2EchoResult() *TestService2EchoResult {
	return &TestService2EchoResult{}
}

func (p *TestService2EchoResult) InitDefault() {
	*p = TestService2EchoResult{}
}

var TestService2EchoResult_Success_DEFAULT *EchoResponse

func (p *TestService2EchoResult) GetSuccess() (v *EchoResponse) {
	if !p.IsSetSuccess() {
		return TestService2EchoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TestService2EchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*EchoResponse)
}

func (p *TestService2EchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestService2EchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestService2EchoResult(%+v)", *p)
}
func (p *TestService2EchoResult) GetResult() interface{} {
	return p.Success
}
